USE TEST;

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'tbl_TEST_CUST' AND [type] = 'u') DROP TABLE tbl_TEST_CUST;

CREATE TABLE tbl_TEST_CUST
(
	CUST_ID			VARCHAR(18) NOT NULL,
	CUST_FRST_NM	VARCHAR(50) NULL,
	CUST_LST_NM		VARCHAR(50) NULL,
	CUST_STREET		VARCHAR(255) NULL,
	CUST_CITY		VARCHAR(50) NULL,
	CUST_STATE		VARCHAR(80) NULL,
	CUST_ZIP		VARCHAR(20) NULL,
	CUST_CMPY_NM	VARCHAR(255) NULL,
	CUST_SPECIALTY	VARCHAR(255) NULL,
 CONSTRAINT [DIMENTSION_LEADSET1] PRIMARY KEY CLUSTERED 
(
	CUST_ID ASC

)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
);